### ISSUE TITLE
Range selection - Changing month/year on first calendar should change second calendar

### ISSUE THREAD

**Issue by mikes-gh** [jdtcn/BlazorDateRangePicker#10]
This is looking really good.

If I change the month or year on the first calendar the second should change to the following month (if it is previous to the first)

eg First calendar July 2021 then the second should also change  to August 2021
eg First calendar December 2019 then the second should also change  to January 2020

Allowing easier range selection.

I realise I should probably do a PR for this but it may not be for a while.
Leaving this here not as a demand but as a note.

**Comment by jdtcn** [comment]
Hi, thanks for your feedback.

There is a `LinkedCalendars` property, that is set to _false_ by default. When it's set to _true_ the two calendars will always display two sequential months.
