### ISSUE TITLE
JS error in console

### ISSUE THREAD

**Issue by steebn** [jdtcn/BlazorDateRangePicker#101]
I am getting the following error in the browser console

`clickAndPositionHandler.js:10 Uncaught SyntaxError: Unexpected token 'export'`

**Comment by jdtcn** [comment]
Hi, what browser are you using?

**Comment by steebn** [comment]
Sorry for the delay. 

I found the issue. The following script tag was placed in the _Host.cshtml file when it shouldn't have:

`<script src="_content/BlazorDateRangePicker/clickAndPositionHandler.js"></script>`

I removed that and it went away. My apologies.
