### ISSUE TITLE
TimePicker24Hour not working on left calendar

### ISSUE THREAD

**Issue by KikoCV** [jdtcn/BlazorDateRangePicker#104]
If u disabled TimePicker24Hour parameter while displaying both a left and right side calendar, the left calendar hour input will still display the 24 hours.

![Captura de ecrã 2024-07-24 130840](https://github.com/user-attachments/assets/d60ca322-99c5-4029-b8e0-443d6cae8cea)

**Comment by jdtcn** [comment]
Thanks for the fix, published it
