### ISSUE TITLE
How to force the second calendar to display next Month in Range When Edit an Item

### ISSUE THREAD

**Issue by lucianparvu** [jdtcn/BlazorDateRangePicker#14]
I want to use the DateRangePicker to save the selected range dates into database. It works perfect when I add a new item lets say a Product, but when I edit one ( Go to a new page /Edit?ProductId=1) the second calendar displays the same Month.

![Calendar](https://user-images.githubusercontent.com/26578147/79893266-7d9aea80-840c-11ea-97c5-ab802d96c977.JPG)

I am missing something ?

My Code:
` <DateRangePicker @bind-StartDate="StartDate" @bind-EndDate="EndDate" Culture="@(System.Globalization.CultureInfo.GetCultureInfo("ro-RO"))" ApplyLabel="@_SharedLocalizer["Apply"]" CancelLabel="@_SharedLocalizer["Cancel"]"></DateRangePicker>

@code {
 DateTimeOffset? StartDate { get; set; } = DateTime.Today.AddMonths(-1);
    DateTimeOffset? EndDate { get; set; } = DateTime.Today.AddDays(1).AddTicks(-1);
}
 protected override async Task OnInitializedAsync()
 {   ....
    var item = await _Service.GetAtributeValueByID(AtributeValueID.Value);
    if (Item.FromDate.HasValue)
    {
        StartDate = Item.FromDate;
    }
    if (Item.ToDate.HasValue)
    {
          EndDate = Item.ToDate;
     }
  }`

**Comment by jdtcn** [comment]
Hello, try `<DateRangePicker LinkedCalendars="true" .... />`

**Comment by lucianparvu** [comment]
Hi, Thank's for answer.

I have Tried but it is not working correctly with LinkedCalendars="true" , looks to be the same problem

- In Add New Item Mode Works correct
- In Edit Mode If I select a date range in first calendar the same date is automatically selected in the second calendar . **But if i change the month from the second calendar , it works correct**

In my opinion the problem is the second calendar because displays the same month. Maybe the End Date should be set in a different way . In My Case Item.FromDate and Item.ToDate are DateTime .

Thank's

**Comment by jdtcn** [comment]
I've found and fixed the issue, just update the package to version 2.3.0

**Comment by lucianparvu** [comment]
Yes, It is working now, I have tested it in many situations. Thank's
