### ISSUE TITLE
Include time selection?

### ISSUE THREAD

**Issue by spyofborg** [jdtcn/BlazorDateRangePicker#16]
Hi,

I see that this is a port of js DateRangePicker.
I noticed in that version it is possible to enable time also, so you can select both dates and times.
Is that something that is already possible or is that a feature TODO?
Sorry if I overlooked it, but I didn't see it in the documentation.

Thank you!

Dj

**Comment by jdtcn** [comment]
Hi,

You're right, time picker isn't implemented. Currently I haven't any plans to implement it.

**Comment by jdtcn** [comment]
Hi,

I've implemented time picker recently, you can check it out [here](https://blazordaterangepicker.azurewebsites.net/time).
