### ISSUE TITLE
Include the possibility of a "Clear" button?

### ISSUE THREAD

**Issue by christian-ruud** [jdtcn/BlazorDateRangePicker#17]
Awsome component. 
It would be great if you could include the option of having a "Clear"-button along with "Apply" and "Cancel" that will set the selected range back to NULL.

**Comment by leninator** [comment]
+1 for this.

One thing I thought would be to use the `type="search"` rather than `type="text"`. You then get the nice little clear button in the textbox by default. However this does cause the popup for the date picker and does not remove any bound values.

**Comment by jdtcn** [comment]
Hello, @christian-ruud!

I've added ButtonsTemplate property in 2.4.0 version, so you can customize picker buttons. See example for your scenario with clear button [in readme file](https://github.com/jdtcn/BlazorDateRangePicker#more-complex-usage).
