### ISSUE TITLE
Show only calendar with out text Box

### ISSUE THREAD

**Issue by novfal** [jdtcn/BlazorDateRangePicker#2]
![image](https://user-images.githubusercontent.com/9216348/65135787-2707a100-da24-11e9-8f0e-f5926d218cb3.png)
how show like this

**Comment by jdtcn** [comment]
````razor
<DateRangePicker>
    <PickerTemplate>
        <div id="@context.ParentId"></div>
    </PickerTemplate>
</DateRangePicker>
````
`id="@context.ParentId"` is necessary for popup position calculations.

**Comment by novfal** [comment]
![image](https://user-images.githubusercontent.com/9216348/65239659-242caf00-dafd-11e9-94f5-a061ca9810b9.png)
calendar visible hidden automatically and calendar placed left top corner of page

**Comment by jdtcn** [comment]
Share the code, please

**Comment by novfal** [comment]
<DateRangePicker @ref="DPRef" Culture="@(System.Globalization.CultureInfo.GetCultureInfo("en-US"))" ApplyLabel="OK" ShowOnlyOneCalendar="true" StartDate="StartDate" EndDate="EndDate" OnRangeSelect="OnRangeSelect">
<PickerTemplate>
        <div id="@context.ParentId"></div>
    </PickerTemplate>
</DateRangePicker>

**Comment by jdtcn** [comment]
Is that all? And where is the closing tag?

It should be something like:
````razor
<DateRangePicker @ref="DPRef" Culture="@(System.Globalization.CultureInfo.GetCultureInfo("en-US"))" ApplyLabel="OK" ShowOnlyOneCalendar="true" StartDate="StartDate" EndDate="EndDate" OnRangeSelect="OnRangeSelect">
    <PickerTemplate>
        <div id="@context.ParentId"></div>
    </PickerTemplate>
</DateRangePicker>
````

And [use the markup ](https://guides.github.com/features/mastering-markdown/)for the code, please.

**Comment by novfal** [comment]
If i click cancel button calendar closed

**Comment by jdtcn** [comment]
You can either hide this button by using the `CancelButtonClasses` property, or reopen the picker when `OnClosed` event is fired.

**Comment by novfal** [comment]
Cancel button shown after set the visibiy hidden also
