### ISSUE TITLE
Inline version

### ISSUE THREAD

**Issue by mselinger75** [jdtcn/BlazorDateRangePicker#20]
Hello, could you please consider making an inline version with just one calendar? Thanks.

**Comment by jdtcn** [comment]
Hello,

I was thinking about this feature too, just needed a trigger. Here it is, so:

in `2.6.0` version:
```razor
<DateRangePicker Inline="true" AutoApply="true" ShowOnlyOneCalendar="true">
    <PickerTemplate>
        @* Empty input template *@
    </PickerTemplate>
</DateRangePicker>
```

`AutoApply` here is to hide buttons, empty picker template means no input field, `ShowOnlyOneCalendar` speaks for itself.
