### ISSUE TITLE
SingleMode - null not set when the date is removed

### ISSUE THREAD

**Issue by cristiteodorov** [jdtcn/BlazorDateRangePicker#21]
Hi, just wondering if there is a way to allow setting the values to null. 

I am using it in single mode - I bind it to a property. When I select a date, my property is updated with the value. When I then delete the value from the input, the property is not set to null, it retains the last "valid" value. 

Is there a way to do this/any plans to add this in the future?

**Comment by jdtcn** [comment]
Hi. You need to bind `EndDate` value to the date property too:

```razor
<DateRangePicker 
    SingleDatePicker="true" 
    @bind-StartDate="StartDate"
    EndDate="StartDate" />

<button @onclick="@(_ => StartDate = null)">Reset</button>
```

**Comment by cristiteodorov** [comment]
Thanks for the suggestion. I was actually trying to achieve this without adding a button.

Just by deleting the text in the input and clicking out -> get a null updated in the "StartDate" model. I think this is not happening at the moment as there are some null checks that prevent the update events from firing.

Do you think this is possible atm without adding the button?

**Comment by jdtcn** [comment]
Sure we can, one way to achieve it is to override `@oninput` event handler behavior:

```razor
<DateRangePicker SingleDatePicker="true" @bind-StartDate="StartDate" EndDate="StartDate">
    <PickerTemplate>
        <input id="@context.ParentId" type="text" value="@context.FormattedRange" 
        @oninput="@(e => OnDpInput(context, e))" @onfocusin="context.Open"
        @onfocusout="context.LostFocus" />
    </PickerTemplate>
</DateRangePicker>
```

And code:
```c#
DateTimeOffset? StartDate { get; set; }
public Task OnDpInput(DateRangePicker context, ChangeEventArgs e)
{
    if (string.IsNullOrEmpty(e?.Value.ToString()))
    {
        StartDate = null;
    }
    else
    {
        return context.OnTextInput(e);
    }
    return Task.CompletedTask;
}
```
