### ISSUE TITLE
How to remove border of the calendar component?

### ISSUE THREAD

**Issue by TheLazyLemur** [jdtcn/BlazorDateRangePicker#25]
Hi.

I would like to remove and or add custom styling to the calendar components itself. Where can this be done?

Thanks

**Comment by jdtcn** [comment]
Hi.

Styles are defined in `daterangepicker(.min).css` file, you're importing it in `_Host.cshtml` (or `index.html`) file:

```html
<link rel="stylesheet" href="_content/BlazorDateRangePicker/daterangepicker.min.css" />
```

Use this file as a base for your custom styling, then replace the link in `_Host.cshtml` to your custom css file.

**Comment by TheLazyLemur** [comment]
Thank you for your reply!
