### ISSUE TITLE
compilerconfig.json artifact added to project on NuGet package install

### ISSUE THREAD

**Issue by pm64** [jdtcn/BlazorDateRangePicker#27]
When the BlazorDateRangePicker NuGet package is installed, compilerconfig.json is created in the project root. I assume this is not intended?

**Comment by jdtcn** [comment]
Hello. Yes, this is not intended. Strange behavior considering this lines in csproj file:

https://github.com/jdtcn/BlazorDateRangePicker/blob/029c5b5da0b1ca664f4e125a45b4a25de00ed0db/BlazorDateRangePicker/BlazorDateRangePicker.csproj#L36-L40

I'll investigate this and publish fix with coming 3.0.0 release within few days.

**Comment by jdtcn** [comment]
Fixed in 2.7.0
