### ISSUE TITLE
enhancement: MinSpan - OnDaySelected Method

### ISSUE THREAD

**Issue by horaciodiez** [jdtcn/BlazorDateRangePicker#29]
Hi again. 
I saw you are planning a 3.0 version.
May you consider...?
1) MinSpan 
For example to avoid the user to select the same Start and EndDate 
2) OnDaySelected
For Example to suggest the EndDate when the StartDate is selected.

Thank you
Regards
H

**Comment by jdtcn** [comment]
Hi.

I've added MinSpan property and OnSelectionStart event in 2.8.0 version.

I'll change major version number after NET 5 release.

**Comment by horaciodiez** [comment]
Hi Sergey.
I´m already using MinSpan.
Thank You!
