### ISSUE TITLE
Calendar overwrite on other component while calendar in open state

### ISSUE THREAD

**Issue by novfal** [jdtcn/BlazorDateRangePicker#3]
![image](https://user-images.githubusercontent.com/9216348/66101340-16326000-e5cc-11e9-8408-08dab26a657a.png)
1)<DateRangePicker DateFormat="dd-MMM-yyyy" style="align-content:center" @ref="DPRef" CloseOnOutsideClick="false" Culture="@(System.Globalization.CultureInfo.GetCultureInfo("en-US"))" ApplyLabel="OK" ShowOnlyOneCalendar="true" StartDate="StartDate" EndDate="EndDate" OnRangeSelect="OnRangeSelect">
              <PickerTemplate>
                <div id="@context.ParentId"></div>
              </PickerTemplate> </DateRangePicker>
2)

**Comment by jdtcn** [comment]
Sorry, I can't reproduce this issue.

Are you using custom markup inside `<DateRangePicker>{here}</DateRangePicker>` tag? If so, show it, please. 

It would be useful if you'll create a repo with the issue reproduction.

**Comment by novfal** [comment]
Nope i did in use markup inside
