### ISSUE TITLE
two-way binding not binds from outside?

### ISSUE THREAD

**Issue by ababars** [jdtcn/BlazorDateRangePicker#32]
markup:
<DateRangePicker @bind-StartDate="Data.Filter.StartDate" @bind-EndDate="Data.Filter.EndDate" AutoApply="true" />

Data - is injectable service with filter object

at first step start and end is a null, after getting first list i've set it to peroid:

Data.Filter.StartDate = new DateTimeOffset(List.Min(m => m.Created));
Data.Filter.EndDate = new DateTimeOffset(List.Max(m => m.Created));

but inputbox still empty: 
![image](https://user-images.githubusercontent.com/8202037/88666110-495c5780-d0e8-11ea-8bc3-b3d33fe1f3b6.png)

if i just open and close without changing dates - it starts to show period: 
![image](https://user-images.githubusercontent.com/8202037/88666159-5c6f2780-d0e8-11ea-9064-fc7936dc492f.png)

**Comment by jdtcn** [comment]
Hi,

I've fixed this issue in 2.9.0 version
