### ISSUE TITLE
Time picker

### ISSUE THREAD

**Issue by ltemimi** [jdtcn/BlazorDateRangePicker#33]
Hi
Can we select time as well?

thanks

**Comment by jdtcn** [comment]
Hi,
Sorry, there is no way to select time with this component, this component is for dates and date ranges only.

**Comment by revenz** [comment]
another +1 for this, or a way to expose a template beneath each calendar so this could be added manually.

**Comment by jdtcn** [comment]
Hi,

I've implemented time picker recently, you can check it out [here](https://blazordaterangepicker.azurewebsites.net/time).
