### ISSUE TITLE
Bug using singleDatePicker

### ISSUE THREAD

**Issue by Thomas-Dimos** [jdtcn/BlazorDateRangePicker#35]
I found this bug while SingleDatePicker is true. If you select a specific date like 18/06/2020 and try to select again the calendar and change month using the arrows the displayed month is incorrect

**Comment by jdtcn** [comment]
Hi, what platform and package version are you using (server-side/wasm/netcore3.1/net5)?
It seems there is a bug in blazor (https://github.com/dotnet/aspnetcore/issues/5616).

I've applied the workaround to the demo app (https://blazordaterangepicker.azurewebsites.net/single).

Can you please check the demo app and confirm that there is no more issue?
If the demo app is fine I'll publish fixed package.

**Comment by Thomas-Dimos** [comment]
Yes i think it's fixed!
