### ISSUE TITLE
Calendar not showing

### ISSUE THREAD

**Issue by ZANZAAA** [jdtcn/BlazorDateRangePicker#36]
Hi,

I would like to use this component in my app however, I can't make it works. The input field is displayed but the calendar doesn't pop when clicking on the field. The app is not a blazor app but a ASP.NET Core WebApp using razor pages & razor components. 

Also the doc on github says that the css and script files should be in the head section but the doc on the [website](https://blazordaterangepicker.azurewebsites.net/) says "near the end of your _Host.cshtml (or index.html for Blazor WebAssembly) pages, right before the closing </body>" I've tried both without success. The issue seems to be with clickAndPositionHandler.js

It works well in my other app (Blazor app web assembly). Any idea why it's not working? Thanks

**Comment by jdtcn** [comment]
Hi,

It's possible to integrate Blazor Components into Existing Asp.Net Core MVC Applications, [this article](https://medium.com/@waelkdouh/integrating-blazor-components-into-existing-asp-net-core-mvc-applications-b1a2aec4ac1f) describes how to add Blazor to your ASP.Net Core middleware. Make sure you're following the steps described in the article.

Place stylesheet `<link>` and `<script>` into your `<head>` section. But the component should work regardless of the `<script>` position, just make sure it loads. 

Working example:
[TestWebApplication.zip](https://github.com/jdtcn/BlazorDateRangePicker/files/5253607/TestWebApplication.zip)

**Comment by ZANZAAA** [comment]
My project has a similar structure to the test project you provided so I reviewed my code again. After further investigation, the problem was due to a conflict between my css and _content/BlazorDateRangePicker/daterangepicker.min.css.

Nothing to do with your package :) Anyway, thanks for your quick reply.
