### ISSUE TITLE
Calendar position and event click

### ISSUE THREAD

**Issue by ZANZAAA** [jdtcn/BlazorDateRangePicker#37]
I found an issue with the calendar popup. When clicking on the field, the calendar open up in the top left corner of the page and won't disappear until you select a date.

It happens when 'DateRangePicker' is used inside the EditForm component. I've created a project to replicate the issue. 

[WebApplicationTest.zip](https://github.com/jdtcn/BlazorDateRangePicker/files/5258981/WebApplicationTest.zip)
![image](https://user-images.githubusercontent.com/45053603/93840179-0bcc1300-fcc2-11ea-9426-a09282096a25.png)

**Comment by jdtcn** [comment]
Hi,

The problem is with `id="Date"` attribute, because it overrides unique id of the  input element. You can use `name="Date"` attribute.
