### ISSUE TITLE
Dark theme or example of dark styling?

### ISSUE THREAD

**Issue by Webreaper** [jdtcn/BlazorDateRangePicker#40]
Love the picker, it's great. However, I need to style it so the backgrounds are dark instead of white. Rather than me reverse-engineer the CSS to figure out which colours I need to change, any chance you could share a dark theme? Or restructure the CSS so that the white background and dark text are defined in one place and can easily be overwritten? :)

**Comment by jdtcn** [comment]
Hi,

I've taken this CSS file from the original daterangepicker js library and keep it untouched to make it backward compatible with tons of CSS customizations made for the original JS component. And there is the dark theme for it, for example: https://gist.github.com/henull/f2beec6095e4329a400abd95f95c21fa

**Comment by Webreaper** [comment]
Awesome, thanks. :)
