### ISSUE TITLE
Clearing the input should set start and end date to null

### ISSUE THREAD

**Issue by Lesterdor** [jdtcn/BlazorDateRangePicker#42]
Hey,
I encountered strange behavior:

If you select a date range, the input will display start - end date (so far, so good). 
If you clear the input field by using backspace key etc. the start and end date property is still set to their values. So clearing the input field has no effect. In my opinion this behavior is not intuitive.

Furthermore if you use `SingleDatePicker = "true"` you have no buttons, so the user cannot reset his chosen date.

You can see what I mean on your documentation:

- [Single Date Picker](https://blazordaterangepicker.azurewebsites.net/single)
- Click on the input field and choose a date
- Clear the input field by using backspace key
- Click the input field again (the date is still selected)

**Comment by jdtcn** [comment]
Hi,
I've fixed this in 3.2.0 version. By the way, there is a way to add reset button to the input: https://github.com/jdtcn/BlazorDateRangePicker/issues/18

**Comment by Lesterdor** [comment]
Hey @jdtcn ,

thank you so much. I've tested the latest version and it works like a charm!

Thanks for your passion and support.
