### ISSUE TITLE
Way to customize a header/footer 

### ISSUE THREAD

**Issue by Lesterdor** [jdtcn/BlazorDateRangePicker#43]
Hey,
Inspired by other DateRangePickers such as [bulma calendar](https://creativebulma.net/product/calendar/demo) I would like to know if you are planning a feature like this? 

I like the idea of being able to create a header or footer if necessary. Tags could be `<HeaderTemplate>` or `<FooterTemplate>`.

Thanks in advance

**Comment by jdtcn** [comment]
Hi,

`<ButtonsTemplate>` is `<FooterTemplate>` you're looking for. As of `HeadterTemplate`, I am not planning any features like this. But you can implement it using inline mode and custom popup with a little of code.
