### ISSUE TITLE
How we can hide Previous Month dates in 1 month calendar?

### ISSUE THREAD

**Issue by anjan-cele** [jdtcn/BlazorDateRangePicker#46]
How we can hide Previous Month dates in 1 month calendar.

![image](https://user-images.githubusercontent.com/13432517/101134349-3b878780-3630-11eb-941a-ab8983decdbb.png)

**Comment by jdtcn** [comment]
Hi, there are at least two options:
1. Using css
```css
.ends {
    visibility: hidden;
}
```

2. Using custom day layout: https://blazordaterangepicker.azurewebsites.net/customDay

Don't forget to override empty cells behavior with https://blazordaterangepicker.azurewebsites.net/customClickHandler

**Comment by anjan-cele** [comment]
Yes it worked. Thanks a lot. Nice Plugin :)
