### ISSUE TITLE
Calendar position is wrong when using it in popover/dialog.

### ISSUE THREAD

**Issue by rui-gong** [jdtcn/BlazorDateRangePicker#48]
Hello,

I am having an issue with the calendar's position when I am using this date range picker inside another component which is a popover/dialog (e.g. bootstrap popovers). The calculated position is relative to the viewport but the calendar itself is relative to the popover, so the calendar shows up at the far right rather than directly below in the input box.

To get around this issue, I have to also pass in the popover so that I can calculate its position, 

`var wrapperElementRect = wrapperElement.getBoundingClientRect();`

together with

`var elementRect = element.getBoundingClientRect();`

I can then find the difference, and use it to get the relative top/right/**left**, and call `setStylesOnElement` to set the inline style on it.

![Calendar position is wrong](https://user-images.githubusercontent.com/75586114/101292029-d02cf800-3871-11eb-8130-6eee4385bb75.PNG)

Do you think that I can address this issue without making this custom change?
Thank you

**Comment by jdtcn** [comment]
Hello,

I'm trying to reproduce the issue. Can you please inform me what popover/dialog library you are using?

**Comment by rui-gong** [comment]
Hi,
I am using [bootstrap 4](https://getbootstrap.com/docs/4.0/components/popovers/)for the popover, it is more like the styles are messed up.

**Comment by jdtcn** [comment]
Hello, I've added a way to solve your issue: https://blazordaterangepicker.azurewebsites.net/container
