### ISSUE TITLE
How to render Date Picker Calendar DOM part only on click of the datepicker input text box.

### ISSUE THREAD

**Issue by anjan-cele** [jdtcn/BlazorDateRangePicker#52]

**Comment by jdtcn** [comment]
Hi,

As you can see [here](https://github.com/jdtcn/BlazorDateRangePicker/blob/master/BlazorDateRangePicker/wwwroot/clickAndPositionHandler.js), I need the picker to be rendered to properly calculate its positioning. To do this, I need the picker to have width and height. If we perform these calculations after clicking input, it will cause the UI to freeze and flicker. So there is no easy way to do it.

**Comment by jdtcn** [comment]
Hi again, I've added `Prerender` property (in version 3.5.0), by setting it to `false` you can avoid initial DOM rendering, first render will occur when the user opens the picker.
