### ISSUE TITLE
After migration to net5.0 from netcore3.2 initially DateRangePicker takes vertical space.  Images attached

### ISSUE THREAD

**Issue by jbetances** [jdtcn/BlazorDateRangePicker#55]
Attached two images that show what happens.  The first is the time the page is loaded.  The second, shows the state after clicking each RangePicker object.  Under netcore3.2, this problem did not occur.
![OnLoadTakesUpSpaceForCalendar](https://user-images.githubusercontent.com/3450798/105803017-7e981400-5f6a-11eb-929e-6c75cc12664d.JPG)
![AfterClickingOnceInEachPicker](https://user-images.githubusercontent.com/3450798/105803018-7e981400-5f6a-11eb-8f05-2b521efc6ec0.JPG)

``<section class="section-check-availability">
    <div class="container">
        <div class="check-availability">
            <div class="row v-align">
                <div class="col-lg-12">
                    <EditForm Model="@availability" OnValidSubmit="Search_Local" class="form-inline">
                        <DataAnnotationsValidator />
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <div class="form-group">
                            <label style="color:white;">Start Date</label>
                            <DateRangePicker class="form-control" SingleDatePicker="true" ShowDropdowns="true"
                                             @bind-StartDate="@availability.CheckinDate" AlwaysShowCalendars="true"
                                             DaysEnabledFunction="@EnabledFunctionCheckin" placeholder="checkin date..." />
                        </div>
                        <div class="form-group">
                            <label style="color:white;">End Date</label>
                            <DateRangePicker class="form-control" SingleDatePicker="true" ShowDropdowns="true"
                                             @bind-StartDate="@availability.CheckoutDate" AlwaysShowCalendars="true"
                                             DaysEnabledFunction="@EnabledFunctionCheckout" placeholder="checkout date..." />
                        </div>
                        <div class="form-group">
                            <label style="color:white;">Guests&nbsp;</label>
                            <select class="form-control" @bind="@availability.NumberOfGuests">
                                <option value="-1" disabled selected>(select)</option>
                                <option value="0">Guests</option>
                                <option value="1">1</option>
                                <option value="2">2</option>
                                <option value="3">3</option>
                                <option value="4">4</option>
                                <option value="5">5</option>
                            </select>
                            <ValidationMessage For="@(() => availability.NumberOfGuests)" />
                        </div>
                        <span class="vailability-submit">
                            <button class="awe-btn awe-btn-13" style="margin:0px 10px 0px 10px" type="submit">Search</button>
                        </span>
                        <span class="vailability-submit">
                            <button type="button" class="awe-btn awe-btn-13" style="margin:0px 10px 0px 10px" @onclick="Cancel">Cancel</button>
                        </span>
                    </EditForm>
                </div>
            </div>
        </div>
    </div>
</section>

**Comment by jdtcn** [comment]
Hi,

looks like CSS issue, I haven't changed CSS styles for a long time, so maybe something changed in other dependencies.

If you're using bootstrap or similar CSS framework, you can just wrap this control with `<div class="d-flex">...</div>` or something similar.

**Comment by jbetances** [comment]
Thanks for your help.  Will try it.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jbetances** [comment]
Tried above suggestion.  It didn't work.

**Comment by jdtcn** [comment]
Can you create sample project to demonstrate this issue, please?

**Comment by jbetances** [comment]
Here is an example that demonstrate the problem. Run it and click on Counter.  You will notice that initially there is a lot of space between the DateRangePicker object & the "Click me" button.  Once you click on the DateRangePicker, the space goes away.  Hope this help.
thanks

**Comment by jbetances** [comment]
[BalozorWASM_ToDO-master.zip](https://github.com/jdtcn/BlazorDateRangePicker/files/5908705/BalozorWASM_ToDO-master.zip)

**Comment by jdtcn** [comment]
Thank you for providing this issue reproduction. So, to solve the issue in this project you either should add css to index.html like that:
```html
<link rel="stylesheet" href="_content/BlazorDateRangePicker/daterangepicker.min.css" />
```
or at least add this style to the project:

```css
.daterangepicker {
    position: absolute;
}
```

**Comment by jbetances** [comment]
That worked.  Thank you so much.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________
