### ISSUE TITLE
AutoApply and TimePicker only works when selecting a Day.

### ISSUE THREAD

**Issue by Dylan-DutchAndBold** [jdtcn/BlazorDateRangePicker#57]
Steps to reproduce:
1. Configure SingleDatePicker = true, TimePicker = true, AutoApply = true
2. Select a day, auto apply works fine.
3. Select a time and then click on a day, auto apply works fine.
4. Now only change the time and click outside of the box. Now time will be reset.

Of course you could argue that it works if you click the day. But just changing the time it does not make sense to click on the day.

I have added a screen recording to demonstrate.

https://user-images.githubusercontent.com/36036362/111633254-961aad00-87f5-11eb-80d5-a9d91da1c144.mov

**Comment by jdtcn** [comment]
Hi, the problem is setting `AutoApply` to `true` should be impossible when `TimePicker` is `true` as in the original daterangepicker js, I'll fix this with the next update.

**Comment by jdtcn** [comment]
I've fixed the issue with 3.6.0 version
