### ISSUE TITLE
Not really an issue but a request

### ISSUE THREAD

**Issue by Redeye51** [jdtcn/BlazorDateRangePicker#6]
I love your date picker for selecting date ranges but is there a way to use this as a single calendar/date selector? I see you can set SingleDatePicker to true but it still tracks both dates. 

Thanks,
Bryan

**Comment by jdtcn** [comment]
Hi, `<DateRangePicker SingleDatePicker="true"></DateRangePicker>` should work (and it's working in demo). If there is an issue, show your code, please.

**Comment by mkopara** [comment]
But is there a way to select multiple single dates (while displaying more then one calendar)?
