### ISSUE TITLE
SingleDatePicker="true" do not show ButtonsTemplate

### ISSUE THREAD

**Issue by lthoa** [jdtcn/BlazorDateRangePicker#61]
Hi,

If set SingleDatePicker="true" and TimePicker="false" the buttons in ButtonsTemplate do nots show.
I need add custom button to reset selected value in SingleDatePicker mode.

**Comment by jdtcn** [comment]
Hi, it's how it was intended in the original js component. You can use the `AutoApply="false"` property to make the buttons appear.

**Comment by lthoa** [comment]
Thanks @jdtcn
