### ISSUE TITLE
Use isolation for JS and CSS?

### ISSUE THREAD

**Issue by christian-ruud-bsafe** [jdtcn/BlazorDateRangePicker#66]
Would really love it if this component could be upgraded to use CSS and JS isolation, eliminating the requirement to add CSS and JS links to host page.

**Comment by jdtcn** [comment]
I have been thinking about doing this for a long time, but have not yet found a way to leave backward compatibility with NET Core 3.1. If I don't find such an opportunity, I will make this change in a year, when support for 3.1 ends.

**Comment by christian-ruud-bsafe** [comment]
One way could be to create a branch for maintaining and bugfixing the current version, and publishing a version 4.0 without .net core 3.1 support. Users of 3.1 could still reference the 3.6 package, and any critical bugfixes could be published as v3.6.x.

Don't know if that's too much hassle.

**Comment by AbstractionsAs** [comment]
Any update on this? Would love for this to be implemented now that 3.1 is out of support

**Comment by jdtcn** [comment]
Hi, good news, finally made css and js isolation in version 5.0.0

**Comment by AbstractionsAs** [comment]
Excellent, thank you!
