### ISSUE TITLE
.NET 6

### ISSUE THREAD

**Issue by Man8earPig** [jdtcn/BlazorDateRangePicker#68]
Looking to utilize some of the improvements of .NET 6 official release in my application, but this package is holding that process back due to the fact that it currently relies on a preview version of .NET 6. 

Any information on when this will be updated to reference the full GA release of .NET 6?

**Comment by jdtcn** [comment]
I will publish a new version tomorrow

**Comment by jdtcn** [comment]
Just published the package, enjoy!
