### ISSUE TITLE
Calendar's wired behaviour while we have both binding and limits

### ISSUE THREAD

**Issue by thatham** [jdtcn/BlazorDateRangePicker#69]
I'm using @bind-StartDate="ViewModel.Model.CheckIn" @bind-EndDate="ViewModel.Model.CheckOut" to set default date selection

**Default Values**
CheckIn = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.AddDays(1).Day),
CheckOut = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.AddDays(7).Day)

and also I set limits so then our users unable to choose beyond provisioned limits

**Limits**
MinDate="DateTimeOffset.Now.AddDays(1)" MaxDate="DateTimeOffset.Now.AddYears(1)"

![image](https://user-images.githubusercontent.com/34929590/146374078-4eb419a3-47a4-44c1-b516-ff19755e2690.png)

above image is the response of the calendar.

**Comment by jdtcn** [comment]
Based on the parameters, everything seems to be correct. What behavior do you expect?

**Comment by thatham** [comment]
If you notice the calendar the month is duplicated. Expected behaviour is
calendar must show Dec and Jan, not Dec and Dec.

**Comment by jdtcn** [comment]
Hello, 

I fixed this issue in version 4.1.0, but please note that your code `CheckOut = new DateTime(DateTime.Now.Year, DateTime.Now.Month, DateTime.Now.AddDays(7).Day)` will not work correctly at the end of December, when there are less than 7 days before the new year. Just use `CheckOut = DateTime.Now.AddDays(7)` and there will be no problem

**Comment by thatham** [comment]
Thank you for your response
