### ISSUE TITLE
How to set the calendar when opening a component set to StartDate in Inline="true" mode?

### ISSUE THREAD

**Issue by Vokchaks** [jdtcn/BlazorDateRangePicker#70]
I use your component with SingleDatePicker="true" and ShowOnlyOneCalendar="true". I set MaxDate, MinDate and StartDate. StartDate is highlighted correctly, but the component opens near to MinDate. I want it to open at the beginning on StartDate. Please help me.

**Comment by jdtcn** [comment]
Hi!

I was unable to reproduce your issue with the latest version of the component. Share your code, please, so I can understand what the problem is. And what version of the component did you use?
