### ISSUE TITLE
Use a ButtonsTemplate with AutoApply=true

### ISSUE THREAD

**Issue by pelshen-bankuet** [jdtcn/BlazorDateRangePicker#74]
I've got a case where I want the `AutoApply` behaviour, but I want the user to be able to clear the dates with a button (no other buttons required). I can create the button required in the `ButtonTemplate` but of course it doesn't show up when `AutoApply` is set to `true`. Is there any way to do what I want or for a change to be made to make it possible?

**Comment by jdtcn** [comment]
This can be done without any problems, since the buttons are simply hidden using a css rule, you just need to redefine it in your component:
```razor
<style>
    .daterangepicker.auto-apply .drp-buttons {
        display: block;
    }
</style>
```

<details>
<summary>It will look something like this</summary>

```razor
<style>
    .daterangepicker.auto-apply .drp-buttons {
        display: block;
    }
</style>

<DateRangePicker @ref="Picker" AutoApply="true" @bind-StartDate="StartDate" @bind-EndDate="EndDate">
    <ButtonsTemplate>
        <button class="cancelBtn btn btn-sm btn-default" @onclick="@(e => ResetClick(e, context))" type="button">
            Reset
        </button>
    </ButtonsTemplate>
</DateRangePicker>

@code {
    DateRangePicker Picker;

    DateTimeOffset? StartDate { get; set; }
    DateTimeOffset? EndDate { get; set; }

    async Task ResetClick(MouseEventArgs e, DateRangePicker picker)
    {
        StartDate = null;
        EndDate = null;
        // Close the picker
        await Picker.Close();
        // Fire OnRangeSelectEvent
        await Picker.OnRangeSelect.InvokeAsync(new DateRange());
    }
}
```

</details>

**Comment by pelshen-bankuet** [comment]
I see, thank you for the reply, that works, very straightforward!
