### ISSUE TITLE
Config doesn't work

### ISSUE THREAD

**Issue by Tommy95271** [jdtcn/BlazorDateRangePicker#75]
Hi, I tried this component and it's really good, lots of demo and properties to use, but when I tried config in Program.cs, it strangely didn't work, is there anything I misunderstood? I'm using .NET 6 and Blazor Server.
`builder.Services.AddDateRangePicker(config =>
{
    config.ApplyButtonClasses = "btn-success";
});`

The Apply button is supposed to be green, yet it's still blue.
![image](https://user-images.githubusercontent.com/55481017/158777158-6c31d9cf-308f-4fbc-a7dc-43153d1e91b6.png)

**Comment by jdtcn** [comment]
Hi,

I tried to reproduce the problem, but the class is successfully applied for me. Maybe it doesn't work in combination with some DateRangePicker parameters? Are you using a custom buttons template? Custom button templates will not be affected by these options. Please share your picker code.

**Comment by Tommy95271** [comment]
Sorry for bothering, it turns out was my mistake, I thought hot reload works on Program.cs, apparently it doesn't, the component works like a charm, thank you!
