### ISSUE TITLE
Does not change DateFormat, TimePicker24Hour and WeekOfDay on Culture change

### ISSUE THREAD

**Issue by marcOcram** [jdtcn/BlazorDateRangePicker#89]
If the Culture changes to another culture the formats and short day names are not updated accordingly. You can see that in the following animation.

The interval above the picker updates correctly.

![DateRangePicker](https://github.com/jdtcn/BlazorDateRangePicker/assets/784604/b8ffcc37-521f-4311-b4ef-c4966e4a8a80)

A (not complete) workaround is to set the `DateFormat`, `TimePicker24Hour` and `FirstDayOfWeek` of `BlazorDateRangePicker` manually. The short day names can not be updated manually as they are set once inside `Calendar`.

A fix would be to update the values of these parameters if the culture changes but only if they are not explicitly set by the user.

**Comment by jdtcn** [comment]
Hello, I fixed this behavior and also made it possible to set your own names for the days. Please check it out in version 4.4.0

**Comment by marcOcram** [comment]
Looks great! Thanks!
