### ISSUE TITLE
Is there a way to select multiple single dates (while displaying more then one calendar)?

### ISSUE THREAD

**Issue by jdtcn** [jdtcn/BlazorDateRangePicker#9]
But is there a way to select multiple single dates (while displaying more then one calendar)?

_Originally posted by @mkopara in https://github.com/jdtcn/BlazorDateRangePicker/issues/6#issuecomment-590832972_

**Comment by jdtcn** [comment]
@mkopara
> 
> 
> But is there a way to select multiple single dates (while displaying more then one calendar)?

Yes, to achieve that you should use a different DateTimeOffset objects for a different picker instances.

Something like that:
```razor
<DateRangePicker StartDate="Start1" EndDate="Start1" SingleDatePicker="true"/>
<DateRangePicker StartDate="Start2" EndDate="Start2" SingleDatePicker="true"/>

@code {
    private DateTimeOffset? Start1 { get; set; } = DateTimeOffset.Now;
    private DateTimeOffset? Start2 { get; set; } = DateTimeOffset.Now;
}
````

**Comment by mkopara** [comment]
Not really the functionality I am aiming.

How about this? 
![calendar_multi_select](https://user-images.githubusercontent.com/15139774/75249246-301c4b80-57d6-11ea-9fdd-fa6256f2e031.png)

**Comment by jdtcn** [comment]
Probably that functionality can be achieved with an `OnRangeSelect` handler, and a custom `CustomDateFunction` that can apply a custom css class from a `CustomDateClass` property to the date. Just apply an `active` class to the dates you want.

**Comment by mkopara** [comment]
Is OnRangeSelect event fired on each date selected, or on range (two dates) selected?


> Probably that functionality can be achieved with an `OnRangeSelect` handler, and a custom `CustomDateFunction` that can apply a custom css class from a `CustomDateClass` property to the date. Just apply an `active` class to the dates you want.

**Comment by jdtcn** [comment]
In the single date mode it fires on each selection.
