### ISSUE TITLE
CSP default-src: self; restricts inline style

### ISSUE THREAD

**Issue by ericbrunner** [jdtcn/BlazorDateRangePicker#95]
Can you remove the inline style and put it in a DataRangePicker.razor.css file to allow the usage of [Content-Security-Policy: default-src 'self';](
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/default-src) ?

As I have seen so far there is only one inline style usage in DateRangePicker.razor

https://github.com/jdtcn/BlazorDateRangePicker/blob/5129c30a9a9e415159c2d36929776915d608a49a/BlazorDateRangePicker/DateRangePicker.razor#L17

Currently when the Content-Security-Policy: default-src 'self'; Header is sent from my Blazor app the inline styles are restricted and your DateRangePicker is opened statically.

Thx.

**Comment by jdtcn** [comment]
Hi, fixed this, now using css class in version 5.0.0, please have a look
